# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn global add wait-on
    - run: yarn install
    - run: yarn bootstrap
    - run: cd packages/client/test/slow && docker compose up -d
    - run: yarn exec wait-on tcp:27017 && yarn invoke dev &
    - run: yarn exec wait-on tcp:3000 && yarn exec wait-on tcp:8080
    - run: yarn invoke test
